import dotenv from "dotenv";
dotenv.config();
// import "./task.consumer";
// import "./log.consumer";
// import "./email.consumer";
// import "./inventory.consume";
// import "./news1.consumer";
// import "./news2.consumer";
// import "./log-topic.consumer";
// import "./notification.consumer";
// import "./work.consumer";
